### ISSUE TITLE
NPE in watchingForItem

### ISSUE THREAD

**Issue by seime** [seaside1/jrule#109]
```
2022-12-28 16:10:35.713 [WARN ] [ab.core.internal.events.EventHandler] - Dispatching/filtering event for subscriber 'org.openhab.core.events.EventSubscriber' failed: null
java.lang.NullPointerException: null
        at org.openhab.automation.jrule.internal.engine.JRuleEngine.lambda$44(JRuleEngine.java:358) ~[?:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at org.openhab.automation.jrule.internal.engine.JRuleEngine.watchingForItem(JRuleEngine.java:356) ~[?:?]
        at org.openhab.automation.jrule.internal.events.JRuleEventSubscriber.processEvent(JRuleEventSubscriber.java:169) ~[?:?]
        at org.openhab.automation.jrule.internal.events.JRuleEventSubscriber.receive(JRuleEventSubscriber.java:147) ~[?:?]
        at org.openhab.core.internal.events.EventHandler.lambda$0(EventHandler.java:151) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

I think I've seen this one a few times, typically at startup.

**Comment by querdenker2k** [comment]
the code does not match to the current master.
It could be this lines
```
List<String> belongingGroups = Optional.of(itemName).map(s -> {
            try {
                return itemRegistry.getItem(s);
            } catch (ItemNotFoundException e) {
                throw new IllegalStateException("this can never occur", e);
            }
        }).map(Item::getGroupNames).orElse(List.of());
```
But this would mean that the itemRegistry is not set

**Comment by seime** [comment]
The code includes PR #100 as well, but I did not check if this PR also includes changes in this class.

**Comment by querdenker2k** [comment]
@seime I never hat this error in the last two months. Does the error occured for you again?

**Comment by seime** [comment]
Yes, I got it yesterday when upgrading to 3.4.2.
