### ISSUE TITLE
NPE in historicState()

### ISSUE THREAD

**Issue by seime** [seaside1/jrule#117]
```
2022-12-30 12:02:40.296 [ERROR] [JRule-Executor-2] [on.jrule.internal.engine.JRuleEngine] - [ruleLog] Error in rule: java.lang.NullPointerException
        at org.openhab.automation.jrule.internal.items.JRuleInternalItem.lambda$0(JRuleInternalItem.java:89)
        at java.base/java.util.Optional.map(Optional.java:265)
        at org.openhab.automation.jrule.internal.items.JRuleInternalItem.getHistoricState(JRuleInternalItem.java:89)

**Comment by querdenker2k** [comment]
@seime Which persistence are you using and what kind of Item?
I tried with rrd4j and SwitchItem but cannot reproduce the error.

**Comment by querdenker2k** [comment]
#118 
I cannot reproduce the error. I never got an NPE. 
@seime Could you check if the test matches your usecase?

**Comment by seime** [comment]
Not seen again, must have been something on my system
