### ISSUE TITLE
JRuleActionClassGen fails on dbquery binding things with NPE after upgrade to BETA16

### ISSUE THREAD

**Issue by espenaf** [seaside1/jrule#142]
I have a dbquery.things with the following. Its to read Influxdb V2 data using the DBQuery binding.

```
Bridge dbquery:influxdb2:palace "InfluxDB2 Bridge" [ bucket="power/autogen", user="admin", url="http://127.0.0.1:8086", organization="Org", token="***" ]{
    Thing dbquery:query:effectNow       "Effect Usage Now"            [ interval=60, hasParameters=false, scalarResult=true, timeout=0, query="from(bucket: \"power/autogen\") |> range(start:-2h) |> filter(fn: (r) => r[\"_measurement\"] == \"Wtot\")  |> filter(fn: (r) => r[\"_field\"] == \"value\") |> distinct() |> last() ", scalarColumn="_value" ]
}
```

After the last update (BETA15 -> BETA16), the following errors showed up in my logs, and generation of all items failed:

```
2023-03-21 18:39:25.253 [ERROR] [le.actions.JRuleActionClassGenerator] - [JRuleActionClassGen] Internal error when generating java source for action dbquery:query:effectNow: java.lang.NullPointerException: ActionInput not s
et on action method parameter
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at org.openhab.automation.jrule.actions.JRuleActionClassGenerator.lambda$6(JRuleActionClassGenerator.java:171)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.openhab.automation.jrule.actions.JRuleActionClassGenerator.lambda$5(JRuleActionClassGenerator.java:166)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.openhab.automation.jrule.actions.JRuleActionClassGenerator.createActionModel(JRuleActionClassGenerator.java:158)
        at org.openhab.automation.jrule.actions.JRuleActionClassGenerator.generateActionSource(JRuleActionClassGenerator.java:65)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.openhab.automation.jrule.internal.handler.JRuleHandler.compileGeneratedSourcesInternal(JRuleHandler.java:330)
        at org.openhab.automation.jrule.internal.handler.JRuleHandler.initialize(JRuleHandler.java:198)
        at org.openhab.automation.jrule.internal.JRuleFactory.init(JRuleFactory.java:82)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by querdenker2k** [comment]
@espenaf Do you want to use this addon with jRule?

**Comment by espenaf** [comment]
> @espenaf Do you want to use this addon with jRule?

That would be nice. I would like to write some rules that use data from influxdb, but if this complicates things I am not relying on anything from this addon in JRule at the moment.

**Comment by seime** [comment]
@espenaf could you give #143 a try and see if it works for you?

**Comment by espenaf** [comment]
> @espenaf could you give #143 a try and see if it works for you?

Looks good. Both my JRules and mye dbquery based items are now working.

**Comment by seime** [comment]
Fixed and merged to main
