### ISSUE TITLE
JRule doesn't work after upgrade OpenHab to 4.0.0

### ISSUE THREAD

**Issue by mziomka** [seaside1/jrule#165]
1. After upgrade OpenHab to 4.0.0 I see error in logs:
```
2023-07-26 20:40:07.042 INFO  e.automation.internal.RuleEngineImpl [OH-ruleengine-1] - Rule engine started.
2023-07-26 20:40:14.547 WARN  org.apache.felix.fileinstall         [fileinstall-/usr/share/openhab/addons] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.automation.jrule-3.x.x-BETA16.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.automation.jrule [262]
  Unresolved requirement: Import-Package: com.sun.org.apache.xml.internal.utils; resolution:="optional"
  Unresolved requirement: Import-Package: com.sun.org.apache.xpath.internal; resolution:="optional"
  Unresolved requirement: Import-Package: com.sun.org.apache.xpath.internal.objects; resolution:="optional"
  Unresolved requirement: Import-Package: org.apache.log; resolution:="optional"
  Unresolved requirement: Import-Package: org.apache.xml.utils; resolution:="optional"
  Unresolved requirement: Import-Package: org.apache.xpath; resolution:="optional"
  Unresolved requirement: Import-Package: org.apache.xpath.objects; resolution:="optional"
  Unresolved requirement: Import-Package: org.dom4j; resolution:="optional"
  Unresolved requirement: Import-Package: org.dom4j.tree; resolution:="optional"
  Unresolved requirement: Import-Package: org.jdom; resolution:="optional"
  Unresolved requirement: Import-Package: org.jdom.input; resolution:="optional"
  Unresolved requirement: Import-Package: org.jdom.output; resolution:="optional"
  Unresolved requirement: Import-Package: org.jaxen; resolution:="optional"
  Unresolved requirement: Import-Package: org.jaxen.dom; resolution:="optional"
  Unresolved requirement: Import-Package: org.jaxen.dom4j; resolution:="optional"
  Unresolved requirement: Import-Package: org.jaxen.jdom; resolution:="optional"
  Unresolved requirement: Import-Package: org.mozilla.javascript; resolution:="optional"
  Unresolved requirement: Import-Package: org.python.core; resolution:="optional"
  Unresolved requirement: Import-Package: org.python.util; resolution:="optional"
  Unresolved requirement: Import-Package: org.zeroturnaround.javarebel; resolution:="optional"
  Unresolved requirement: Import-Package: org.apache.tools.ant; resolution:="optional"
  Unresolved requirement: Import-Package: org.apache.tools.ant.taskdefs; resolution:="optional"
  Unresolved requirement: Import-Package: javax.el

        at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.18.0.jar:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) ~[?:?]
```

2. When I try to download automaticlly from http://localhost:8181/settings/addons I see:
```
2023-07-26 18:59:46.350 WARN  ity.CommunityMarketplaceAddonService [OH-addonService-1] - Could not determine bundle name from url: https://github.com/seaside1/jrule/releases/latest/download/org.openhab.automation.jrule-3.x.x-latest.jar
```

PS. I apologize for my not very good and frugal English :)
Michał

**Comment by querdenker2k** [comment]
You have to use a build for openhab 4. The current main builds are working for openhab 4.

**Comment by seaside1** [comment]
Yes and the market version is still on OH 3.  Now with the OH official 4.0 release, I'll build one for 4.0
