### ISSUE TITLE
ConcurrentModificationException while listening for events

### ISSUE THREAD

**Issue by seime** [seaside1/jrule#72]
```
2022-11-01 19:30:19.550 [WARN ] [ab.core.internal.events.EventHandler] - Dispatching/filtering event for subscriber 'org.openhab.core.events.EventSubscriber' failed: null
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1634) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528) ~[?:?]
        at org.openhab.automation.jrule.internal.engine.JRuleEngine.watchingForItem(JRuleEngine.java:330) ~[?:?]
        at org.openhab.automation.jrule.internal.events.JRuleEventSubscriber.processEvent(JRuleEventSubscriber.java:169) ~[?:?]
        at org.openhab.automation.jrule.internal.events.JRuleEventSubscriber.receive(JRuleEventSubscriber.java:147) ~[?:?]
        at org.openhab.core.internal.events.EventHandler.lambda$0(EventHandler.java:151) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

I assume new events may occure while starting JRule and adding ExecutionContexts

**Comment by querdenker2k** [comment]
I would assume this as well. We should synchronize all access to contextList.
