### ISSUE TITLE
Race condition when Precondition changed right before Rule triggers

### ISSUE THREAD

**Issue by seaside1** [seaside1/jrule#88]
I noticed the build fails. I get the same failure locally.
@querdenker2k  Can you invesigate?

```

3:09:39.756 [docker-java-stream--578458950] INFO  docker.mqtt - STDERR: 1668341379: Sending CONNACK to ITJRule (0, 0)
[ERROR] Tests run: 12, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 88.453 s <<< FAILURE! - in org.openhab.automation.jrule.rules.integration_test.ITJRule
[ERROR] org.openhab.automation.jrule.rules.integration_test.ITJRule.preconditionExecution  Time elapsed: 0.406 s  <<< ERROR!
MqttException (0)
	at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.restoreBackups(MqttDefaultFilePersistence.java:276)
	at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.open(MqttDefaultFilePersistence.java:126)
	at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(ConnectActionListener.java:174)
	at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.onFailure(ConnectActionListener.java:137)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.fireActionEvent(CommsCallback.java:326)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleActionComplete(CommsCallback.java:260)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.asyncOperationComplete(CommsCallback.java:445)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:418)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:170)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by querdenker2k** [comment]
https://github.com/seaside1/jrule/pull/91

**Comment by seaside1** [comment]
On my i7-6600U it builds fine every time. 
On my new Ryzen 5650U Pro it fails sometimes with concurrentmodification exception

Git failed to build but does not look as the same error.
Attaching log.
[pr77fail-short.txt](https://github.com/seaside1/jrule/files/10006598/pr77fail-short.txt)

**Comment by seaside1** [comment]
Git fail: https://github.com/seaside1/jrule/actions/runs/3464517045/jobs/5786135117

**Comment by querdenker2k** [comment]
I think this git fail (https://github.com/seaside1/jrule/actions/runs/3464517045/jobs/5786135117) is a timing problem.
See the following log snippet:
```
STDOUT: 19:32:17.159 [DEBUG] [internal.events.JRuleEventSubscriber] - [+JRuleSubscriber+] Received event 'ItemCommandEvent' with topic 'openhab/items/Precondition_String/command' and payload '{"type":"String","value":"that matches"}'
STDOUT: 19:32:17.160 [DEBUG] [on.jrule.internal.engine.JRuleEngine] - [+JRuleEngine+] watching for item: 'Precondition_String'? -> false
STDOUT: 19:32:17.164 [DEBUG] [internal.events.JRuleEventSubscriber] - [+JRuleSubscriber+] Received event 'ItemCommandEvent' with topic 'openhab/items/Preconditioned_Switch/command' and payload '{"type":"OnOff","value":"ON"}'
STDOUT: 19:32:17.165 [DEBUG] [on.jrule.internal.engine.JRuleEngine] - [+JRuleEngine+] watching for item: 'Preconditioned_Switch'? -> true
STDOUT: 19:32:17.165 [DEBUG] [internal.events.JRuleEventSubscriber] - [+JRuleSubscriber+] Event processed as PROPERTY_ITEM_EVENT: topic openhab/items/Preconditioned_Switch/command payload: {"type":"OnOff","value":"ON"}
STDOUT: 19:32:17.170 [DEBUG] [eItemReceivedCommandExecutionContext] - [+JRuleItemReceivedCommandExecutionContext+] does it match?: JRuleItemReceivedCommandExecutionContext{command=Optional.empty, itemName='Preconditioned_Switch', memberOf=false, gt=Optional.empty, gte=Optional.empty, lt=Optional.empty, lte=Optional.empty, eq=Optional.empty, neq=Optional.empty, logName='precondition execution', jRule=org.openhab.automation.jrule.rules.user.TestRules@714ede77, method=public void org.openhab.automation.jrule.rules.user.TestRules.preconditionExecution(org.openhab.automation.jrule.rules.event.JRuleItemEvent), loggingTags=[], preconditionContextList=[JRulePreconditionContext{item='Precondition_String', lt=Optional.empty, lte=Optional.empty, gt=Optional.empty, gte=Optional.empty, eq=Optional[that matches], neq=Optional.empty}]}, Item 'Preconditioned_Switch' received command ON, JRuleAdditionalItemCheckData{belongingGroups=[]}
STDOUT: 19:32:17.171 [DEBUG] [on.jrule.internal.engine.JRuleEngine] - [+JRuleEngine+] precondition mismatch: will not match = that matches
STDOUT: 19:32:17.171 [DEBUG] [internal.events.JRuleEventSubscriber] - [+JRuleSubscriber+] Received event 'ItemStateEvent' with topic 'openhab/items/Precondition_String/state' and payload '{"type":"String","value":"that matches"}'
STDOUT: 19:32:17.172 [DEBUG] [on.jrule.internal.engine.JRuleEngine] - [+JRuleEngine+] watching for item: 'Precondition_String'? -> false
STDOUT: 19:32:17.174 [DEBUG] [internal.events.JRuleEventSubscriber] - [+JRuleSubscriber+] Received event 'ItemStateEvent' with topic 'openhab/items/Preconditioned_Switch/state' and payload '{"type":"OnOff","value":"ON"}'
STDOUT: 19:32:17.174 [DEBUG] [on.jrule.internal.engine.JRuleEngine] - [+JRuleEngine+] watching for item: 'Preconditioned_Switch'? -> true
STDOUT: 19:32:17.174 [DEBUG] [internal.events.JRuleEventSubscriber] - [+JRuleSubscriber+] Event processed as PROPERTY_ITEM_EVENT: topic openhab/items/Preconditioned_Switch/state payload: {"type":"OnOff","value":"ON"}
STDOUT: 19:32:17.182 [DEBUG] [eItemReceivedCommandExecutionContext] - [+JRuleItemReceivedCommandExecutionContext+] does it match?: JRuleItemReceivedCommandExecutionContext{command=Optional.empty, itemName='Preconditioned_Switch', memberOf=false, gt=Optional.empty, gte=Optional.empty, lt=Optional.empty, lte=Optional.empty, eq=Optional.empty, neq=Optional.empty, logName='precondition execution', jRule=org.openhab.automation.jrule.rules.user.TestRules@714ede77, method=public void org.openhab.automation.jrule.rules.user.TestRules.preconditionExecution(org.openhab.automation.jrule.rules.event.JRuleItemEvent), loggingTags=[], preconditionContextList=[JRulePreconditionContext{item='Precondition_String', lt=Optional.empty, lte=Optional.empty, gt=Optional.empty, gte=Optional.empty, eq=Optional[that matches], neq=Optional.empty}]}, Item 'Preconditioned_Switch' updated to ON, JRuleAdditionalItemCheckData{belongingGroups=[]}
STDOUT: 19:32:17.182 [DEBUG] [internal.events.JRuleEventSubscriber] - [+JRuleSubscriber+] Received event 'ItemStateChangedEvent' with topic 'openhab/items/Precondition_String/statechanged' and payload '{"type":"String","value":"that matches","oldType":"String","oldValue":"will not match"}'
STDOUT: 19:32:17.183 [DEBUG] [on.jrule.internal.engine.JRuleEngine] - [+JRuleEngine+] watching for item: 'Precondition_String'? -> false

```
In line 1+2 the precondition is set to the correct state -> no action, just the precondition
In line 3+4 the rule will be triggered, but in line 7 the precondition fails because the old value is still in the precondition item.
Just in line 8 there is the update event that the precondition item state will be updated.
Am I right with this analysis? That means that there is a problem in real life scenarios when the precondition fires millis before the rule trigger fires.
I let the test run for 30 minutes in a endless loop and get no errors, nevertheless i added a sleep between this two sendCommands (precondition and trigger item) to be sure that this timing/race condition will not occur. But we should discuss  this problem.

**Comment by seaside1** [comment]
I think we can close this one now right?

**Comment by querdenker2k** [comment]
But the described problem can still occur

**Comment by seaside1** [comment]
Fair enough, lets see if we can fix it.

**Comment by seime** [comment]
Is this still an issue?

**Comment by querdenker2k** [comment]
i think this can occur but improbable in real life scenarios.
But i think its a timing problem coming from openhab core.
a command is fired but the item state is not change before so a race condition can occur.
I see just an option to cache commands as states but this would be a workaround for the openhab doing.
I think we should close this for now.
